<!-- formulario de alta de tarea -->
<form action="agregar" method="POST" class="my-5">
    <div class="row">
        <div class="col-3">
            <div class="form-group">
                <label>Tren: </label>
                <input required name="tren" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Musculo:</label>
                <input required name="musculo" type="text" class="form-control">
            </div>
        </div>
        
        <div class="col-3">
            <div class="form-group">
                <label>Ejercicio</label>
                <input required name="ejercicio" type="text" class="form-control">
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar ejercicio</button>
</form>
