<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Musculatrix - Gimnasio</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="main">MUSCULATRIX</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <?php if (!isset($_SESSION['CLIENTE_ID'])) : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="login">Login</a>
                            </li>
                        <?php elseif ($_SESSION['CLIENTE_ID']==1) : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="admin">Admin</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="desloguear">Logout</a>
                            </li>
                        <?php else : ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="desloguear">Logout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="rutinas">Rutinas</a>
                                </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <!-- inicio main container -->
    <main class="container mt-3">
